[changelog]
header = """# Changelog\n"""
body = """
{% for group, commits in commits | group_by(attribute="group") %}
## {{ group | upper_first }}

{% for commit in commits %}
- {{ commit.message | upper_first }} ([{{ commit.id | truncate(length=7) }}])
{% endfor %}
{% endfor %}
"""

trim = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = true
tag_pattern = "v[0-9]*"
