def data_quality_report_cont(dataframe):
    """
    Generates a data quality report for continuous features in a given DataFrame.

    This function calculates and prints the following metrics for each feature in the provided list:
    - Total count of non-missing values
    - Total count of missing values
    - Percentage of missing values
    - Cardinality (number of unique values)
    - Descriptive statistics (e.g., mean, standard deviation, min, max) for each feature

    Parameters:
    -----------
    dataframe : pandas.DataFrame
        The DataFrame containing the data to be analyzed.
    list_of_features : list of str
        The list of column names (features) for which the data quality report is generated.

    Returns:
    --------
    None
        This function prints the data quality report to the console.

    Docstring generated by ChatGPT.
    """
    # Initialize variables
    round_to = 2
    list_feature_name = []
    list_count = []
    list_missing = []
    list_percent = []
    list_cardinality = []

    # Create list of non-categorical values
    list_of_features = dataframe.select_dtypes(
        exclude=['category', 'object']).columns.tolist()

    if len(list_of_features ) == 0:
        print("This dataset does not have any non-categorical features.")
        return

    print("The non-categorical features are: ")
    print(list_of_features)

    for feature in list_of_features:
        # Get stats for each feature
        total_count = dataframe[feature].count()
        total_missing = dataframe[feature].isnull().sum()
        percent_missing = total_missing/total_count * 100
        cardinality = len(dataframe[feature].unique())

        # Append result to variables
        list_feature_name.append(feature)
        list_count.append(total_count)
        list_missing.append(total_missing)
        list_percent.append(np.round(percent_missing, round_to))
        list_cardinality.append(cardinality)

    # Create dataframe
    data = {
        "Feature": list_feature_name,
        "Count": list_count,
        "Missing": list_missing,
        "% missing": list_percent,
        "Cardinality": list_cardinality
    }
    df = pd.DataFrame(data)

    # Get descriptive statistics and transpose
    stats = np.round(dataframe[list_of_features].describe(), round_to)
    transposed_stats = stats.T

    # Print results
    print("Data Quality for Continous Features")
    print(f'Total Features: {len(list_of_features)}')
    print(df)

    print("\n")
    print("Descriptive Stats")
    print(transposed_stats)

    return

def data_quality_report_cat(dataframe):
    """
    Generates a data quality report for categorical features in a given DataFrame.

    This function calculates and prints the following metrics for each feature in the provided list:
    - Total count of non-missing values
    - Total count of missing values
    - Percentage of missing values
    - Cardinality (number of unique values)
    - Mode 1 (most frequent value) and its frequency and percentage
    - Mode 2 (second most frequent value) and its frequency and percentage
    - Descriptive statistics for each feature

    Parameters:
    -----------
    dataframe : pandas.DataFrame
        The DataFrame containing the data to be analyzed.
    list_of_features : list of str
        The list of column names (features) for which the data quality report is generated.

    Returns:
    --------
    None
        This function prints the data quality report to the console.
    
    Docstring generated by ChatGPT.
    """
    # Initialize variables
    round_to = 2
    list_feature_name = []
    list_count = []
    list_missing = []
    list_percent = []
    list_cardinality = []
    list_mode1 = []
    list_mode1_freq = []
    list_mode1_perc = []
    list_mode2 = []
    list_mode2_freq = []
    list_mode2_perc = []

    # Create list of non-categorical values
    list_of_features = dataframe.select_dtypes(
        include=['category', 'object']).columns.tolist()

    if len(list_of_features) == 0:
        print("This dataset does not have any categorical columns.")
        return

    print("The categorical features are: ")
    print(list_of_features)
        
    for feature in list_of_features:
        
        total_count = dataframe[feature].count()
        total_missing = dataframe[feature].isnull().sum()
        percent_missing = np.round(total_missing / total_count * 100, round_to)
        cardinality = len(dataframe[feature].unique())

        # Use value counts to get modes
        results = dataframe[feature].value_counts()
        # Calculate mode
        mode1_name = results.index[0]
        mode1_count = results.iloc[0]
        mode1_percent = np.round((mode1_count / total_count) * 100, round_to)
        # Calculate 2nd mode
        mode2_name = results.index[1]
        mode2_count = results.iloc[1]
        mode2_percent = np.round((mode2_count / total_count) * 100, round_to)

        # Append results to lists
        list_feature_name.append(feature)
        list_count.append(total_count)
        list_missing.append(total_missing)
        list_percent.append(percent_missing)
        list_cardinality.append(cardinality)
        list_mode1.append(mode1_name)
        list_mode1_freq.append(mode1_count)
        list_mode1_perc.append(mode1_percent)
        list_mode2.append(mode2_name)
        list_mode2_freq.append(mode2_count)
        list_mode2_perc.append(mode2_percent)

    # Create dataframes
    data = {
        "Feature": list_feature_name,
        "Count": list_count,
        "Missing": list_missing,
        "% Missing": list_percent,
        "Cardinality": list_cardinality,
    }

    data_mode1 = {
        "Feature": list_feature_name,
        "Mode 1": list_mode1,
        "Mode 1 Freq.": list_mode1_freq,
        "Mode 1 %": list_mode1_perc,
    }

    data_mode2 = {
        "Feature": list_feature_name,
        "Mode 2": list_mode2,
        "Mode 2 Freq.": list_mode2_freq,
        "Mode 2 %": list_mode2_perc,
    }

    df = pd.DataFrame(data)
    df1 = pd.DataFrame(data_mode1)
    df2 = pd.DataFrame(data_mode2)

    # Get descriptive statistics and transpose
    stats = dataframe[list_of_features].describe(include='object')
    transposed_stats = stats.T

    # Print results
    print('Data Quality Report for Categorical Features')
    print('============================================')
    print('Stats')
    print('-----')
    print(df)

    print('\n')
    print('Mode 1')
    print('------')
    print(df1)

    print('\n')
    print('Mode 2')
    print('------')
    print(df2)

    print('\n')
    print('Descriptive Stats')
    print('-----------------')
    print(transposed_stats)

    return 

