site_name: jcds Library

theme:
  name: material

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - API Reference: api.md
  - Changelog: changelog.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_signature_annotations: true
          paths: ["."]